name: 'Build and Deploy'

on:
  push:
    branches:
      - main
      - develop

permissions: 
  contents: write

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF##*/})
      - name: Build
        uses: ./.github/actions/container_run
        with:
          cont_action: 'build'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          branch: main
          repository-name: aquemy/aquemy.github.io
          token: ${{ secrets.ACCESS_TOKEN }}
