name: 'Build and Deploy'

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch::$(echo ${GITHUB_REF##*/})
      - name: Build
        uses: ./.github/actions/container_run
        with:
          cont_action: 'build'
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: output
          branch: main
          repo: aquemy/aquemy.github.io
          token: ${{ secrets.ACCESS_TOKEN }}
